# Generated by Django 3.0.1 on 2020-01-17 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package_tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='status_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
