# Generated by Django 3.0.1 on 2020-01-17 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package_tracking', '0003_package_status_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='status_text',
            field=models.CharField(default='Unknowm', max_length=200),
        ),
    ]
